// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jegrcycalczdtnpomtwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplZ3JjeWNhbGN6ZHRucG9tdHdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODAwMDQsImV4cCI6MjA2NTE1NjAwNH0.gi5rRF_i69wmFIBtaBALBTaQBIaJVk1Pej9VSu54i8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);